version: '3.8'
services:
  # nodeapp:
  #   build: .
  #   container_name: nodeapp
  #   environment:
  #     - NODE_ENV=development
  #     - ES_HOST=http://elasticsearch:9200   # Node connects to Elasticsearch here
  #   ports:
  #     - "8001:8002"  # Node app available at http://localhost:3001
  #   depends_on:
  #     - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m   # lightweight for MacBook Air
      - xpack.security.enabled=false     # disable auth for dev
    ports:
      - "9200:9200"  # Elasticsearch available at http://localhost:9200
    volumes:
      - es_data:/Users/vincentluciani/Software/elastic
     #- /Users/thisisme/Software/elastic:/usr/share/elasticsearch/data
     # need chmod -R 777 /Users/thisisme/Software/elastic
    # command: >
    #   sh -c "
    #     sleep 10 && \
    #     curl -X PUT 'http://localhost:9200/us' -H 'Content-Type: application/json' -d '
    #     {
    #       \"settings\": {
    #         \"analysis\": {
    #           \"analyzer\": {
    #             \"my_analyzer\": {\"tokenizer\": \"my_tokenizer\"},
    #             \"simple_analyzer\": {\"tokenizer\":\"standard\",\"filter\":[\"synonym\",\"stemmer\",\"uppercase\",\"my_custom_stop_words_filter\"]}
    #           },
    #           \"tokenizer\": {
    #             \"my_tokenizer\": {\"type\": \"ngram\",\"min_gram\":3,\"max_gram\":3,\"token_chars\":[\"letter\",\"digit\"]}
    #           },
    #           \"filter\": {
    #             \"my_custom_stop_words_filter\": {\"type\":\"stop\",\"ignore_case\":true,\"stopwords\":[\"a\",\"is\",\"the\"]},
    #             \"synonym\": {\"type\":\"synonym\",\"lenient\":true,\"synonyms\":[\"remove,delete\",\"change,modify\"]}
    #           }
    #         }
    #       },
    #       \"mappings\": {
    #         \"properties\": {
    #           \"category\": {\"type\": \"keyword\"},
    #           \"subCategory\": {\"type\": \"keyword\"},
    #           \"question\": {\"type\": \"text\", \"analyzer\":\"simple_analyzer\"},
    #           \"answer\": {\"type\": \"text\", \"analyzer\":\"simple_analyzer\"}
    #         }
    #       }
    #     }'
    #   "
volumes:
  es_data:
    driver: local
