#!/bin/bash
# generate-package-json.sh - detect dependencies and create a package.json

# 1. Find external dependencies (ignore relative imports like "./" or "../")
deps=$(grep -RhoE "require\(['\"][^'\"]+['\"]\)|from ['\"][^'\"]+['\"]" . \
  | sed -E "s/require\(['\"]([^'\"]+)['\"]\)/\1/; s/from ['\"]([^'\"]+)['\"]/\1/" \
  | grep -vE "^(\.|/)" \
  | sort -u)

# 2. Prepare dependencies block in JSON
deps_json=""
for dep in $deps; do
  # Default to "*" version so npm resolves the latest compatible version
  deps_json="$deps_json\"$dep\": \"*\",\n"
done

# Trim last comma
deps_json=$(echo -e "$deps_json" | sed '$ s/,$//')

# 3. Create package.json
cat > package.json <<EOF
{
  "name": "autogenerated-app",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "dependencies": {
$(echo -e "$deps_json")
  }
}
EOF

echo "✅ package.json generated with detected dependencies!"
echo "👉 Run: npm install"
